services:
  db:
    image: postgres:15
    container_name: postgresql
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - db

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - graphql
      - db

  service-a:
    build:
      context: ./grpc
      dockerfile: service-a/Dockerfile
    container_name: service-a
    ports:
      - "50051:50051"
    env_file:
      - ./.env
    depends_on:
      - db

  service-b:
    build:
      context: ./grpc
      dockerfile: service-b/Dockerfile
    container_name: service-b
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - service-a

volumes:
  db_data:
